"""Add time and price fields to events

Revision ID: 52fe9e7ce2e5
Revises: 001_initial
Create Date: 2026-02-01 12:38:30.701166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52fe9e7ce2e5'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_registrations_id'), 'event_registrations', ['id'], unique=False)
    op.add_column('events', sa.Column('time', sa.String(length=50), nullable=True))
    op.add_column('events', sa.Column('price', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', name='userrole'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('user', 'admin', name='userrole'),
               existing_nullable=False)
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_column('events', 'price')
    op.drop_column('events', 'time')
    op.drop_index(op.f('ix_event_registrations_id'), table_name='event_registrations')
    # ### end Alembic commands ###
