"""Add admin fields

Revision ID: c12b22f02b7f
Revises: 52fe9e7ce2e5
Create Date: 2026-02-01 13:37:25.706293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12b22f02b7f'
down_revision: Union[str, None] = '52fe9e7ce2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('map_link', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('registration_deadline', sa.DateTime(), nullable=True))
    op.add_column('events', sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_published')
    op.drop_column('events', 'registration_deadline')
    op.drop_column('events', 'map_link')
    # ### end Alembic commands ###
